config/routes.rb
BankingApp::Application.routes.draw do
  
  match '/home', :to => 'pages#home'
  match '/list', :to => 'accounts#index'
  match '/open', :to => 'accounts#new'
  match 'accounts/:id/deposit' => 'accounts#deposit'
  match 'accounts/:id/withdrawal' => 'accounts#withdrawal'
  match 'accounts/:id/transfer' => 'accounts#transfer'
  match 'accounts/:id/show2' => 'accounts#show2'
  match '/hw1', :to => 'pages#hw1'
  match '/exit', :to => 'pages#exit'
  
  root :to => 'pages#home'
 
  resources :accounts do 
     member do 
       get 'deposit'
       get 'withdrawal'
       get 'transfer'
       get 'show2'
     end
  end

  resources :customers

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "List Accounts", list_path %></li>
      <li><%= link_to "Open Account", open_path %></li>
      <li><%= link_to "Deposit", list_path %></li>
      <li><%= link_to "Withdrawal", list_path %></li>
      <li><%= link_to "Transfer", list_path %></li>
      <li><%= link_to "Exit", exit_path %></li>
    </ul>
  </nav>
  <p>
  <nav class="round">
  This is a Ruby on Rails site built based on the <%= link_to "Ruby on Rails Tutorial", "http://railstutorial.org/ruby-on-rails-tutorial-book" %>. </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("logo.png", :alt => "Banking App", :class => "round") %>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "HW1 Assignment", hw1_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>