config/routes.rb
BankingApp::Application.routes.draw do
  
  match '/home', :to => 'pages#home'
  match '/list', :to => 'accounts#index'
  match '/open', :to => 'accounts#new'
  match 'accounts/:id/deposit' => 'accounts#deposit'
  match 'accounts/:id/withdrawal' => 'accounts#withdrawal'
  match 'accounts/:id/transfer' => 'accounts#transfer'
  match 'accounts/:id/show2' => 'accounts#show2'
  match '/hw1', :to => 'pages#hw1'
  match '/exit', :to => 'pages#exit'
  
  root :to => 'pages#home'
 
  resources :accounts do 
     member do 
       get 'deposit'
       get 'withdrawal'
       get 'transfer'
       get 'show2'
     end
  end

  resources :customers

end

app/models/account.rb
# == Schema Information
# Schema version: 20110210002527
#
# Table name: accounts
#
#  id         :integer         not null, primary key
#  last_name  :string(255)
#  first_name :string(255)
#  address    :string(255)
#  phone      :string(255)
#  soc_sec    :string(255)
#  amount     :decimal(, )
#  created_at :datetime
#  updated_at :datetime
#

class Account < ActiveRecord::Base
  ssn_regex = /^[0-9]{3}-[0-9]{2}-[0-9]{4}$/
  phone_regex = /^[0-9]{3}-[0-9]{3}-[0-9]{4}$/

  validates :last_name, :presence => true,
            			:length => { :maximum => 30 }
  validates :first_name, :presence => true,
  						:length => { :maximum => 30 }
  validates :address, :presence => true
  validates :phone, :presence => true,
  					:format => { :with => phone_regex 	}
  validates :soc_sec, :presence => true,
  					  :format => { :with => ssn_regex,
  					               :message => "SSN must be in 999-99-9999 format."},
  					  :uniqueness => true
  validates :amount, :presence => true,
                     :numericality => { :greater_than => 0 }
                     
  def full_name
    self.first_name + " " + self.last_name
  end
  
  def full_name_with_acct_num
    self.id.to_s + " - " + self.full_name
  end
  
  def deposit (amount) 
    self.update_attributes(:amount => self.amount + amount)
  end
  
  def withdraw (amount) 
    self.update_attributes(:amount => self.amount - amount)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # needed for number_to_currency method
  include ActionView::Helpers::NumberHelper

  # GET /accounts
  # GET /accounts.xml
  def index
    # Set per_page to 3 to demonstrate pagination functionality with few accounts
    @accounts = Account.paginate(:page => params[:page], :per_page => 3, :order => 'created_at')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.xml
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.xml
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.xml
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to(@account, :notice => "Account #{@account.id} was successfully created.") }
        format.xml  { render :xml => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to(@account, :notice => "Account #{@account.id} was successfully updated.") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def deposit
    @account = Account.find(params[:id])

    respond_to do |format|
      if (amount = params[:dep_amount])
        amount = amount.to_f
        @account.deposit(amount)
        format.html { redirect_to(@account, :notice => "Account #{@account.id} was successfully updated.") }
        format.xml  { head :ok }
      else
        format.html { render :action => "deposit" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /accounts/1
  # PUT /accounts/1.xml
  def withdrawal
    @account = Account.find(params[:id])

    respond_to do |format|
      if (amount = params[:withd_amount])
        amount = amount.to_f
        if (amount <= @account.amount)
           @account.withdraw(amount)
           format.html { redirect_to(@account, :notice => "Account #{@account.id} was successfully updated.") }
           format.xml  { head :ok }
        else
           @error = "Amount may not exceed the account balance."
           format.html { render :action => "withdrawal" }
           format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
        end
      else
        format.html { render :action => "withdrawal" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def transfer
    # Transfer from account1
    @account1 = Account.find(params[:id])
    # A temp array for the options menu - all accounts except account1
    @not_account1 = Account.all.reject{|x| x == @account1 }

    respond_to do |format|
      if (amount = params[:transfer_amount])
        @account2 = Account.find(params[:account2_id])
        amount = amount.to_f
        @account1.withdraw(amount)
        @account2.deposit(amount)
        amount = number_to_currency(amount, :unit => "$")
        @notice = amount + " was successfully transferred from account " + @account1.id.to_s + " to account " + @account2.id.to_s + "."
        format.html { render (:action => "show2") }
        format.xml  { head :ok }
      else
        format.html { render :action => "transfer" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show2
     #@account1 = Account.find(params[:id])
     #@account2 = Account.find(params[:account2_id])
     respond_to do |format|
      format.html # show2.html.erb
    end
  end


  # DELETE /accounts/1
  # DELETE /accounts/1.xml
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to(accounts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def AmountUpdate (account, amount) 
     account.update_attributes(:amount => (account.amount + amount))
  end
end

app/views/accounts/_dep_form.html.erb
<% form_tag(:action => 'deposit', :method=>'post') do %>
  <% if @error %>
    <div id="error_explanation">
      <ul>
        <li><%= @error %></li>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Amount:
    <%= number_field_tag "dep_amount", nil, :min => 0.01 ,:max => @account.amount %>
  </div>
  <div class="actions">
    <%= submit_tag "Deposit" %>
  </div>
<% end %>

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name, "Last Name" %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name, "First Name" %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :soc_sec, "Social Security Number" %><br />
    <%= f.text_field :soc_sec %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/_transfer_form.html.erb
<% form_tag(:action => 'transfer', :method=>'post') do %>
  <div class="field">
    To account: 
    
    <%= collection_select(:account, :id, @not_account1, :id, 
                          :full_name_with_acct_num, {}, :name => "account2_id") %>
  <div>
    
  <div class="field">
    Amount:  <%= number_field_tag "transfer_amount", nil, :min => 0.01 %>
  </div>

  <br />

  <div class="actions">
    <%= submit_tag "Transfer" %>
  </div>

<% end %>

app/views/accounts/_withd_form.html.erb
<% form_tag(:action => 'withdrawal', :method=>'post') do %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @error %>
    <div id="error_explanation">
      <ul>
        <li><%= @error %></li>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Amount:
    <%= number_field_tag "withd_amount", nil, :min => 0.01 ,:max => @account.amount %>
  </div>
  <div class="actions">
    <%= submit_tag "Withdraw" %>
  </div>
<% end %>

app/views/accounts/deposit.html.erb
<h1>Deposit into account <%= @account.id %></h1>
<h3>Current amount <%= number_to_currency(@account.amount, :unit => "$") %></h3>

<%= render 'dep_form' %>
<br><br>
<%= link_to "Cancel", list_path %>

app/views/accounts/edit.html.erb
<h1>Editing account <%= @account.id %></h1>

<%= render 'form' %>
<br><br>
<%= link_to "Cancel", list_path %>

app/views/accounts/index.html.erb
<h1>List Accounts</h1>


<%= will_paginate %>
<br />

<table>
  <tr>
    <th>Account Number</th>
    <th>Last Name</th>
    <th>First Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Social Security Number</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<% @accounts.each do |account| %>
  <tr>
    <td><%= account.id %></td>
    <td><%= account.last_name %></td>
    <td><%= account.first_name %></td>
    <td><%= account.address %></td>
    <td><%= account.phone %></td>
    <td><%= account.soc_sec %></td>
    <td><%= number_to_currency(account.amount, :unit => "$") %></td>
    <td><%= link_to 'Deposit', deposit_account_path(account) %>
    <td><%= link_to 'Withdrawal', withdrawal_account_path(account) %>
    <td><%= link_to 'Transfer', transfer_account_path(account) %>
  </tr>
<% end %>


</table>

<br />

<%= will_paginate %>

app/views/accounts/new.html.erb
<h1>Open Account</h1>

<%= render 'form' %>
<br><br>
<%= link_to "Cancel", home_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Account Number:</b>
  <%= @account.id %>
</p>

<p>
  <b>Last Name:</b>
  <%= @account.last_name %>
</p>

<p>
  <b>First Name:</b>
  <%= @account.first_name %>
</p>

<p>
  <b>Address:</b>
  <%= @account.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @account.phone %>
</p>

<p>
  <b>Social Security Number:</b>
  <%= @account.soc_sec %>
</p>

<p>
  <b>Amount:</b>
  <%= number_to_currency(@account.amount, :unit => "$") %>
</p>

app/views/accounts/show2.html.erb
<p id="notice"><%= @notice %></p>

<table>

<tr>
<td><b>Account Number:</b></td>
<td><%= @account1.id %></td>
<td><%= @account2.id %></td>
</tr>

<tr>
<td><b>Last Name:</b></td>
<td><%= @account1.last_name %></td>
<td><%= @account2.last_name %></td>
</tr>

<tr>
<td><b>First Name:</b></td>
<td><%= @account1.first_name %></td>
<td><%= @account2.first_name %></td>
</tr>

<tr>
<td><b>Amount:</b></td>
<td><%= number_to_currency(@account1.amount, :unit => "$") %></td>
<td><%= number_to_currency(@account2.amount, :unit => "$") %></td>
</tr>

</table>

app/views/accounts/transfer.html.erb
<h1>Transfer from account <%= @account1.id %></h1>
<h3>Current amount <%= number_to_currency(@account1.amount, :unit => "$") %></h3>

<%= render 'transfer_form' %>
<br><br>
<%= link_to "Cancel", list_path %>

app/views/accounts/withdrawal.html.erb
<h1>Withdraw from account <%= @account.id %></h1>
<h3>Current amount <%= number_to_currency(@account.amount, :unit => "$") %></h3>

<%= render 'withd_form' %>
<br><br>
<%= link_to "Cancel", list_path %>